routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function(){
  return redirect('web');
});
Route::get('/panitia','WebpanitiaController@index');
Route::get('/kandidat','WebkandidatController@index');
Route::get('/about','WebaboutController@index');
Route::group(['prefix'=>'web'], function(){
  Route::get('/','WebController@index');
});
Auth::routes();

//Route::get('/home', 'HomeController@index');
Route::group(['middleware' => 'auth'], function () {
  Route::get('/home', 'HomeController@index');
  Route::get('/home/users','UserController@index');
  Route::get('/home/panitia','PanitiaController@index');
  Route::get('/home/karya', 'KaryaIlmiahController@index');
  Route::get('/home/kandidat', 'KandidatController@index');
  Route::get('/home/coment', 'ComentController@index');
  Route::get('/home/visi', 'VisiController@index');
  Route::get('/home/misi', 'MisiController@index');
  Route::get('/home/voting', 'VotingController@index');
  Route::get('/home/vote', 'VoteController@getIndex');

  Route::group(['prefix'=>'users'], function(){
    Route::get('home/users','UserController@index');
    Route::get('create','UserController@create');
    Route::post('create','UserController@submit');
    Route::get('edit/{id}','UserController@edit');
    Route::post('edit/{id}','UserController@update');
    Route::get('delete/{id}','UserController@delete');

  });

  Route::group(['prefix'=>'panitia'], function(){
    Route::get('home/panitia','PanitiaController@index');
    Route::get('create','PanitiaController@create');
    Route::post('create','PanitiaController@submit');
    Route::get('edit/{id}','PanitiaController@edit');
    Route::post('edit/{id}','PanitiaController@update');
    Route::get('delete/{id}','PanitiaController@delete');

  });
Route::group(['prefix'=>'karya'], function(){
    Route::get('home/karya','KaryaIlmiahController@index');
    Route::get('create','KaryaIlmiahController@create');
    Route::post('create','KaryaIlmiahController@submit');
    Route::get('edit/{id}','KaryaIlmiahController@edit');
    Route::post('edit/{id}','KaryaIlmiahController@update');
    Route::get('delete/{id}','KaryaIlmiahController@delete');

});
  Route::group(['prefix'=>'kandidat'], function(){
      Route::get('home/kandidat','KandidatController@index');
      Route::get('create','KandidatController@create');
      Route::post('create','KandidatController@submit');
      Route::get('edit/{id}','KandidatController@edit');
      Route::post('edit/{id}','KandidatController@update');
      Route::get('delete/{id}','KandidatController@delete');
      Route::get('detail/{id}','KandidatController@detail');
  });

  Route::group(['prefix'=>'coment'], function(){
      Route::get('home/coment','ComentController@index');
      Route::get('create','ComentController@create');
      Route::post('create','ComentController@submit');
      Route::get('edit/{id}','ComentController@edit');
      Route::post('edit/{id}','ComentController@update');
      Route::get('delete/{id}','ComentController@delete');
  });

  Route::group(['prefix'=>'visi'], function(){
      Route::get('home/visi','VisiController@index');
      Route::get('create','VisiController@create');
      Route::post('create','VisiController@submit');
      Route::get('edit/{id}','VisiController@edit');
      Route::post('edit/{id}','VisiController@update');
      Route::get('delete/{id}','VisiController@delete');
  });

  Route::group(['prefix'=>'misi'], function(){
      Route::get('home/misi','MisiController@index');
      Route::get('create','MisiController@create');
      Route::post('create','MisiController@submit');
      Route::get('edit/{id}','MisiController@edit');
      Route::post('edit/{id}','MisiController@update');
      Route::get('delete/{id}','MisiController@delete');
  });

  Route::group(['prefix'=>'voting'], function(){
      Route::get('home/voting','VotingController@index');
      Route::get('create','VotingController@create');
      Route::post('create','VotingController@submit');
      Route::get('edit/{id}','VotingController@edit');
      Route::post('edit/{id}','VotingController@update');
      Route::get('delete/{id}','VotingController@delete');
  });

  Route::group(['prefix'=>'vote'], function(){
    Route::get('home/vote','VoteController@getindex');
      Route::get('read','VoteController@getRead');
      Route::post('create','VoteController@postRead');
      Route::post('create','VoteController@save');
      Route::get('delete/{id}','VoteController@delete');
  });


    Route::group(['prefix'=>'users'], function(){
      Route::get('/home/users','UserController@index');
      Route::get('create','UserController@create');
      Route::post('create','UserController@submit');
      Route::get('delete/{id}','UserController@delete');
    });
      //Route::get('remove','PanitiaController@remove');
  });

app/Voting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Voting extends Model
{
    protected $table = 'voting';
    protected $fillable = ['calon_id', 'jumlah'];
    protected $appends = ['display_calon'];

    public function Kandidat()
    {
      return $this->belongsTo('App\Kandidat', 'calon_id');
    }

    public function getDisplayCalonAttribute()
    {
        $kandidat = $this->kandidat;
        if($kandidat){
            $format = ' %s -  %s';
            return sprintf($format, $kandidat->ketua, $kandidat->wakil);
        }else{
            return 'Tidak ada kandidat';
        }
    }

    public function getKandidatNomorAttribute()
    {
      return object_get($this->kandidat, 'nomor', '-');
    }
}

app/Http/Controllers/VotingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Voting;
use App\kandidat;
class VotingController extends Controller
{
    public function __construct(Voting $voting, Kandidat $kandidat, Request $request)
    {
      $this->voting = $voting;
      $this->kandidat = $kandidat;
      $this->request = $request;
    }

    public function index()
    {
      $voting = Voting::all();

      return view('manager.voting.index', compact('voting'));
    }

    public function create()
    {
      $kandidat = Kandidat::pluck('nomor', 'id');

      return view('manager.voting.form', compact('kandidat'));
    }

    public function submit(Request $request)
    {
      $voting = new Voting;
      $this->validate($request, [
        'calon_id' => 'required'
      ]);

      $voting->calon_id = $this->request['calon_id'];
      $voting->jumlah = 0;
      $voting->save();

      return redirect('home\voting');
    }

    public function delete($id)
    {
         $voting = $this->voting->findOrFail($id);
         $voting->delete();
          return redirect('home/voting');
    }

    public function edit($id)
    {
      $voting = Voting::find($id);
      $kandidat = Kandidat::pluck('nomor', 'id');
      return view('manager.voting.edit',compact('voting' ,'kandidat'));
    }

    public function update(Request $request, $id)
    {
      $this->validate($request,[
        'calon_id' => 'required',
      ]);
      $voting = Voting::find($id);
      $votingUpdate = $request->all();
      $voting->update($votingUpdate);
      return redirect('home/voting');
    }
}

resources/views/manager/voting/edit.blade.php
@extends('manager.layout.index')
@section('content')
<ol class="breadcrumb">
  <li><a href="{{url('/home')}}">Home</a></li>
  <li><a href="{{url('/home/misi')}}">Misi</a></li>
  <li class="active">Form Misi</li>
</ol>
  <div class="page-header">
    <h3>Input Data Misi</h3>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          Misi
        </div>
          <div class="panel-body">
            {!! Form::open() !!}
            {!! Form::model($voting) !!}

            <div class="form-group{{ $errors->has('misi') ? ' has-error' : '' }}">
            <div class="form-group{{ $errors->has('calon_id') ? ' has-error' : '' }}">
              {!! Form::label('calon ') !!}
              {!! Form::select('calon_id', $kandidat, old('calon_id'),['class'=>'form-control']) !!}
              @if ($errors->has('calon_id'))
                  <span id="helpBlock2" class="help-block">
                      <strong>{{ $errors->first('calon_id') }}</strong>
                  </span>
              @endif
            </div>
            <br>
            <button type="submit" class="btn btn-primary btn-sm">Submit</button>
            {!! Form::close() !!}
          </div>
      </div>
    </div>
  </div>

@endsection

resources/views/manager/voting/form.blade.php
@extends('manager.layout.index')
@section('content')
<ol class="breadcrumb">
  <li><a href="{{url('/home')}}">Home</a></li>
  <li><a href="{{url('/home/voting')}}">Voting</a></li>
  <li class="active">Form Voting</li>
</ol>
  <div class="page-header">
    <h3>Input Data Voting</h3>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          Misi
        </div>
          <div class="panel-body">
            {!! Form::open() !!}

            <div class="form-group{{ $errors->has('voting') ? ' has-error' : '' }}">
            <div class="form-group{{ $errors->has('calon_id') ? ' has-error' : '' }}">
              {!! Form::label('calon ') !!}
              {!! Form::select('calon_id', $kandidat, old('calon_id'),['class'=>'form-control']) !!}
              @if ($errors->has('calon_id'))
                  <span id="helpBlock2" class="help-block">
                      <strong>{{ $errors->first('calon_id') }}</strong>
                  </span>
              @endif
            </div>
            <br>
            <button type="submit" class="btn btn-primary btn-sm">Submit</button>
            {!! Form::close() !!}
          </div>
      </div>
    </div>
  </div>

@endsection

resources/views/manager/voting/index.blade.php
@extends('manager.layout.index')
@section('content')
<div class="page-header">
  <h3>Voting</h3>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <button class="btn btn-default btn-sm"><a href="{{url('/voting/create')}}" style="color:black;text-decoration:none;"><i class="fa fa-plus"></i> Tambah</a></button>
  </div>
  <div class="panel-body">

  <table class="table table-default">
    <thead>
      <tr>
        <th>id</th>
        <th>Nomor Urut</th>
        <th>Jumlah Vote</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      @foreach($voting as $index=>$item)
      <tr>
        <td>{{$item->id}}</td>
        <td>{{$item->kandidat_nomor}}</td>
        <td>{{$item->jumlah}}</td>
        <td>
          <a href="{{url('voting/delete',[$item->id])}}" onclick="return confirm('Anda yakin akan menghapus data ini ?');" class="btn btn-danger btn-sm">Hapus</a>
          <a href="{{url('voting/edit',[$item->id])}}" class="btn btn-primary btn-sm">edit</a>
        </td>

      </tr>
      @endforeach
    </tbody>
  </table>
</div>
</div>
@endsection